### ISSUE TITLE
Pls remove the Blues embarrassing loss from Saturday night

### ISSUE THREAD

**Issue by Snepsts** [chintans1/hockey-app#3]
You will notice the README here:

![image](https://user-images.githubusercontent.com/8688876/58815796-df344980-85ed-11e9-9bc3-b4e919218301.png)

It looks pretty good, right? But on closer inspection...

![image](https://user-images.githubusercontent.com/8688876/58816001-3d612c80-85ee-11e9-96f6-eb657483f88e.png)

What's this?

![image](https://user-images.githubusercontent.com/8688876/58815837-f5420a00-85ed-11e9-8445-e4fe04462b7e.png)

Oh no! It's a memory of that very horrific game Saturday night!

I ask you to remove this as it is a hate crime against Saint Louisians. That was a painful and sad hockey game that gives me nightmares.

Thank you and have a good day Chintan.

Also, your app looks sick bro.

**Comment by chintans1** [comment]
Lmao they won the cup so everything is fine! Thanks!
